#Build Stage
FROM python:3.11-slim AS build
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
  && rm -rf /var/lib/apt/lists/* 
RUN python3 -m venv /venv && /venv/bin/pip install --upgrade pip setuptools wheel

#Build-venv
FROM build AS build-venv
COPY requirements.txt .
RUN /venv/bin/pip install --disable-pip-version-check -r requirements.txt

#Runtime Stage
FROM python:3.11-slim
RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*
RUN groupadd -g 1000 appgroup && \
    useradd -u 1000 -g appgroup -m -s /bin/bash appuser
WORKDIR /app
COPY --from=build-venv /venv /venv
COPY . /app
RUN chown -R appuser:appgroup /app
ENV PATH="/venv/bin:$PATH"
USER appuser
EXPOSE 8003
HEALTHCHECK --interval=30s --timeout=10s --retries=3 \
  CMD curl -f http://localhost:8003/health || exit 1
ENTRYPOINT ["python", "-m", "gunicorn", "--bind", "0.0.0.0:8003", "app:app"]

